name: Auto Publish NuGet

on:
  push:
    tags:
      - 'v*.*.*'  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Read current version from tag
      id: version
      run: |
        TAG_NAME="${GITHUB_REF##*/}"  
        echo "Tag name: $TAG_NAME"
        
        IFS='.' read -r MAJOR MINOR PATCH <<< "${TAG_NAME:1}"  
        echo "Current version from tag: $MAJOR.$MINOR.$PATCH"
        
        PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "New version: $NEW_VERSION"
        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Check and Update version in cs-owm.csproj
      run: |
        TAG_NAME="${GITHUB_REF##*/}"  
        echo "Tag name: $TAG_NAME"
        
        IFS='.' read -r MAJOR MINOR PATCH <<< "${TAG_NAME:1}"  
        echo "Current version from tag: $MAJOR.$MINOR.$PATCH"
        FILE="cs-owm.csproj"
        
        CURRENT_VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" "$FILE")
        echo "Current version in cs-owm.csproj: $CURRENT_VERSION"
        
        if [[ "$CURRENT_VERSION" != "$MAJOR.$MINOR.$PATCH" ]]; then
          echo "Version mismatch, updating version in cs-owm.csproj..."
          sed -i "s|<Version>.*</Version>|<Version>$MAJOR.$MINOR.$PATCH</Version>|" "$FILE"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b update-version
          git add cs-owm.csproj
          git commit -m "Auto bump version .csproj file to $MAJOR.$MINOR.$PATCH"
          git push origin update-version
        else
          echo "Version already up-to-date, no update needed."
        fi

    - name: Create pull request
      run: |
        TAG_NAME="${GITHUB_REF##*/}"
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"title":"Auto bump version to '"$TAG_NAME"'","head":"update-version","base":"main"}' \
          https://api.github.com/repos/${{ github.repository }}/pulls

    - name: Build & Pack
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet pack --configuration Release --no-build -o ./nupkgs

    - name: Push to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
